rlfrkdms1/coding-test

rlfrkdms1/백준/Silver3/가희와_키워드.java

[250127] [Silver3] 22233번 가희와 키워드

---

rlfrkdms1/백준/Silver2/최소_힙.java

[250129] [Silver2] 1927번 최소 힙

---

rlfrkdms1/백준/Silver2/랭킹전_대기열.java

[250130] [Silver2] 20006번 랭킹전 대기열

---

rlfrkdms1/백준/Silver2/주식.java

[0202] [Silver2] 11501번 주식

---

rlfrkdms1/백준/Silver2/에디터.java

[250203] [Silver2] 1406번 에디터

---

hcu55/week02/창고다각형.java

⭐️⭐️가장 높은 부분이 여러 개 있다는 사실을 주의해야함

[250204] 창고 다각형(impl), 실버 II

---

rlfrkdms1/백준/Silver2/창고_다각형.java

[250204] [Silver2] 2304번 창고 다각형

---

rlfrkdms1/백준/Silver3/N번째_큰_수.java

[250205] [Silver3] 2075번 N번째 큰 수

---

rlfrkdms1/백준/Silver2/한_줄로_서기.java

[250206] [Silver2] 1138번 한 줄로 서기

---

rlfrkdms1/백준/Silver2/DFS와_BFS.java

[250210] [Silver2] 1260번 DFS와 BFS

---

rlfrkdms1/백준/Silver1/쉬운_최단거리.java

[250211] [Silver1] 14940번 쉬운 최단거리

---

rlfrkdms1/백준/Silver1/겹치는_건_싫어.java

[250212] [Silver1] 20922번 겹치는 건 싫어

---

rlfrkdms1/백준/Silver1/지름길.java

[Silver1] [250213] 1446번 지름길

---

hcu55/week03/지름길.java

다익스트라 알고리즘
- 가중치가 있는 그래프에서 최단 경로를 찾는 알고리즘
- 음수 가중치가 없는 경우에 사용할 수 있음
- 우선순위 큐(PriorityQueue, 최소 힙)를 활용
- `if (현재 거리 > 저장된 거리) continue;` 조건을 활용하여 불필요한 연산을 줄이는 것이 중요

[250213] 지름길(dijkstra), 실버 I

---

rlfrkdms1/백준/Silver1/회전초밥.java

[250217] [Silver1] 2531번 회전초밥

---

rlfrkdms1/백준/Silver1/문자열_교환.java

[250218] [Silver1] 1522번 문자열 교환

---

rlfrkdms1/백준/Silver1/단축키_지정.java

[250220] [Silver1] 1283번 단축키 지정

---

rlfrkdms1/백준/Silver1/숨바꼭질.java

[250219] [Silver1] 1697번 숨바꼭질

---

rlfrkdms1/백준/Gold5/1_2_3_더하기_4.java

[250223] [Gold5] 15989번 1, 2, 3 더하기 4

---

rlfrkdms1/백준/Gold5/숨바꼭질_3.java

[250224] [Gold5] 13549번 숨바꼭질 3

---

rlfrkdms1/백준/Gold5/A와_B_2.java

[250225] [Gold5] 12919번 A와 B 2

---

rlfrkdms1/백준/Gold5/컨베이어_벨트_위의_로봇.java

[250226] [Gold5] 20055번 컨베이어 벨트 위의 로봇

---

rlfrkdms1/백준/Gold5/뱀과_사다리_게임(우선순위_큐).java
rlfrkdms1/백준/Gold5/뱀과_사다리_게임.java

[250227] [Gold5] 16928번 뱀과 사다리 게임

---

rlfrkdms1/백준/Gold5/문자열_게임_2.java

[250228] [Gold5] 20437번 문자열 게임 2

---

rlfrkdms1/백준/Gold5/탑.java

[250303] [Gold5] 2493번 탑

---

rlfrkdms1/백준/Gold5/빗물.java

[250304] [Gold5] 14719번 빗물

---

rlfrkdms1/백준/Gold5/용액.java

[250306] [Gold5] 2467번 용액

---

rlfrkdms1/백준/숫자고르기.java

[250309] [Gold5] 2668번 숫자고르기

---

rlfrkdms1/백준/Gold5/빌런_호석.java

[250311] [Gold5] 22251번 빌런 호석

---

rlfrkdms1/백준/Gold5/0_만들기.java

[250312] [Gold5] 7490번 0 만들기

---

rlfrkdms1/백준/Gold4/전구와_스위치.java

[250314] [Gold4] 2138번 전구와 스위치

---

rlfrkdms1/백준/Gold4/스카이라인_쉬운거.java

[250317] [Gold4] 1863번 스카이라인 쉬운거

---

rlfrkdms1/백준/Gold4/좋다.java

[250319] [Gold4] 1253번 좋다

---

rlfrkdms1/백준/Gold4/부분합.java

[250320] [Gold4] 1806번 부분합

---

rlfrkdms1/백준/Gold4/알파벳.java

[250323] [Gold4] 1987번 알파벳

---

rlfrkdms1/백준/Gold4/공유기_설치.java

[250324] [Gold4] 2110번 공유기 설치

---

rlfrkdms1/백준/Gold4/문자열_폭발(Stack-get()).java
rlfrkdms1/백준/Gold4/문자열_폭발.java

[250325] [Gold4] 9935번 문자열 폭발

---

rlfrkdms1/백준/Gold4/List_of_Unique_Numbers.java

[250326] [Gold4] 13144번 List of Unique Numbers

---

rlfrkdms1/백준/고층_건물.java

[250328] [Gold4] 1027번 고층 건물

---

rlfrkdms1/백준/Gold4/여행_가자.java

[250327] [Gold4] 1976번 여행 가자

---

hcu55/week09/여행가자.java

[250327] 여행 가자(Union find), 골드 IV

---

rlfrkdms1/백준/Gold4/비슷한_단어.java

[250329] [Gold4] 2179번 비슷한 단어

---

rlfrkdms1/백준/Gold4/줄세우기.java

[250402] [Gold4] 2631번 줄세우기

---

rlfrkdms1/백준/Gold3/파티.java

[250404] [Gold3] 1238번 파티

---

rlfrkdms1/백준/Gold3/하늘에서 별똥별이 빗발친다.java

[250406] [Gold3] 14658번 하늘에서 별똥별이 빗발친다

---

rlfrkdms1/백준/Gold3/탑_보기.java

[250408] [Gold3] 22866번 탑 보기

---

rlfrkdms1/백준/Gold3/감시.java

[250410] [Gold3] 15683번 감시

---

rlfrkdms1/백준/Gold3/가희와_탑.java

[250409] [Gold3] 24337번 가희와 탑

---

hcu55/week11/감시.java

[250410] 감시(dfs+impl), 골드 III

---

hcu55/week12/동전분배.java

https://blog.naver.com/adamdoha/222086394461 참고

[250413] 동전 분배(dp+Knapsack), 골드 II

---

rlfrkdms1/백준/Gold2/1의_개수_세기.java

[250415] [Gold2] 9527번 1의 개수 세기

---

rlfrkdms1/백준/Gold2/성냥개비.java

[250417] [Gold2] 3687번 성냥개비

---

rlfrkdms1/백준/Gold2/보석_도둑.java

[250423] [Gold2] 1202번 보석 도둑

---

rlfrkdms1/백준/Gold1/횡단보도.java

[250424] [Gold1] 24042번 횡단보도

---

hcu55/week14/그래프트리분할.java

[250427] 그래프 트리 분할(tree), 골드 I

---

rlfrkdms1/백준/Gold5/평범한_배낭.java

[250501] [Gold5] 12865번 평범한 배낭

---

rlfrkdms1/백준/Platinum5/등산_마니아.java

[250429] [Platinum5] 20188번 등산 마니아

---

rlfrkdms1/백준/Platinum5/백조의_호수.java

[250505] [Platinum5] 3197번 백조의 호수

---

rlfrkdms1/백준/Gold1/이항_계수_3.java

[250508] [Gold1] 11401번 이항 계수 3
